//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupeA07.Models
{
	using GroupeA07.DAO;
	using System;
    using System.Collections.Generic;
	using System.Data.SqlClient;

	public partial class Member
    {
        public int idUser { get; set; }
        public string emailUser { get; set; }
        public string username { get; set; }
        public string userPwd { get; set; }
        public byte userAdmin { get; set; }

	}


}
