//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupeA07.Models
{
	using GroupeA07.DAO;
	using System;
    using System.Collections.Generic;
	using System.Data.SqlClient;

	public class Member
    {
        public int idUser { get; set; }
        public string emailUser { get; set; }
        public string username { get; set; }
        public string userPwd { get; set; }
        public byte userAdmin { get; set; }

		public Member() { }

		public Member(SqlDataReader reader)
		{
			idUser = Int32.Parse(reader[MemberDAO.COLUMN_ID_USER].ToString());
			emailUser = reader[MemberDAO.COLUMN_EMAIL_USER].ToString();
			username = reader[MemberDAO.COLUMN_USER_NAME].ToString();
			userPwd = reader[MemberDAO.COLUMN_USER_PWD].ToString();

			userAdmin = Byte.Parse(reader[MemberDAO.COLUMN_USER_ADMIN].ToString());
		}
	}


}
