//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupeA07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_user
    {
        public int idSeller { get; set; }
        public string username { get; set; }
        public Nullable<int> nbSales { get; set; }
        public Nullable<int> positiveVote { get; set; }
        public Nullable<int> negativeVote { get; set; }
        public Nullable<int> idUser { get; set; }
    }
}
